#!/bin/bash

# Cycle the layout on the current active workspace between dwindle, master, and scrolling

ACTIVE_WORKSPACE=$(hyprctl activeworkspace -j | jq -r '.id')
CURRENT_LAYOUT=$(hyprctl activeworkspace -j | jq -r '.tiledLayout')

case "$CURRENT_LAYOUT" in
  dwindle) 
    NEW_LAYOUT="master" 
    ;;
  master) 
    NEW_LAYOUT="scrolling" 
    ;;
  scrolling) 
    NEW_LAYOUT="dwindle" 
    ;;
  *) 
    # Fallback in case the layout is null or unassigned
    NEW_LAYOUT="dwindle" 
    ;;
esac

hyprctl keyword workspace "$ACTIVE_WORKSPACE", layout:"$NEW_LAYOUT"
notify-send "󱂬    Workspace layout set to $NEW_LAYOUT"
