CompileFlags:
  Add: [-std=c++20]
  
Index:
  StandardLibrary: Yes

Diagnostics:
  UnusedIncludes: Strict
  
InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Completion:
  AllScopes: Yes
