[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"
