[font]
size = 12.8

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"
